version: '2'
services:
    hubshifts-app:
        image: hubshifts
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://hubshifts-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=hubshifts
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hubshifts-mongodb:
        extends:
            file: mongodb.yml
            service: hubshifts-mongodb
